language: node_js
node_js:
  - "10"
install:
  - npm i
before_script:
  - npm run build
deploy:
  local-dir: ./dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
branches:
  only:
  - master
